import "./globals.css";
import { Inter } from "next/font/google";
import Header from "./header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="select-none text-white bg-zinc-900 w-[100svw] h-[100svh] overflow-hidden">
        <Header />
        <main className="w-full h-screen flex flex-col"> {children}</main>
      </body>
    </html>
  );
}
